/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as PortalWorkoutsRouteImport } from './routes/portal/workouts'
import { Route as PortalWeightRouteImport } from './routes/portal/weight'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalExercisesRouteImport } from './routes/portal/exercises'
import { Route as PortalDietRouteImport } from './routes/portal/diet'
import { Route as CoachTrainingRouteImport } from './routes/coach/training'
import { Route as CoachSubscriptionsRouteImport } from './routes/coach/subscriptions'
import { Route as CoachSchedulesRouteImport } from './routes/coach/schedules'
import { Route as CoachProductsRouteImport } from './routes/coach/products'
import { Route as CoachGalleriesRouteImport } from './routes/coach/galleries'
import { Route as CoachDietRouteImport } from './routes/coach/diet'
import { Route as CoachClientsRouteImport } from './routes/coach/clients'
import { Route as CoachClientsClientIdRouteImport } from './routes/coach/clients_.$clientId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const PortalWorkoutsRoute = PortalWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWeightRoute = PortalWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExercisesRoute = PortalExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDietRoute = PortalDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => PortalRoute,
} as any)
const CoachTrainingRoute = CoachTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => CoachRoute,
} as any)
const CoachSubscriptionsRoute = CoachSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => CoachRoute,
} as any)
const CoachSchedulesRoute = CoachSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => CoachRoute,
} as any)
const CoachProductsRoute = CoachProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => CoachRoute,
} as any)
const CoachGalleriesRoute = CoachGalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => CoachRoute,
} as any)
const CoachDietRoute = CoachDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientsRoute = CoachClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientsClientIdRoute = CoachClientsClientIdRouteImport.update({
  id: '/clients_/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach': typeof CoachRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/shop': typeof ShopRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/diet': typeof CoachDietRoute
  '/coach/galleries': typeof CoachGalleriesRoute
  '/coach/products': typeof CoachProductsRoute
  '/coach/schedules': typeof CoachSchedulesRoute
  '/coach/subscriptions': typeof CoachSubscriptionsRoute
  '/coach/training': typeof CoachTrainingRoute
  '/portal/diet': typeof PortalDietRoute
  '/portal/exercises': typeof PortalExercisesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/weight': typeof PortalWeightRoute
  '/portal/workouts': typeof PortalWorkoutsRoute
  '/coach/': typeof CoachIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/diet': typeof CoachDietRoute
  '/coach/galleries': typeof CoachGalleriesRoute
  '/coach/products': typeof CoachProductsRoute
  '/coach/schedules': typeof CoachSchedulesRoute
  '/coach/subscriptions': typeof CoachSubscriptionsRoute
  '/coach/training': typeof CoachTrainingRoute
  '/portal/diet': typeof PortalDietRoute
  '/portal/exercises': typeof PortalExercisesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/weight': typeof PortalWeightRoute
  '/portal/workouts': typeof PortalWorkoutsRoute
  '/coach': typeof CoachIndexRoute
  '/portal': typeof PortalIndexRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach': typeof CoachRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/shop': typeof ShopRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/diet': typeof CoachDietRoute
  '/coach/galleries': typeof CoachGalleriesRoute
  '/coach/products': typeof CoachProductsRoute
  '/coach/schedules': typeof CoachSchedulesRoute
  '/coach/subscriptions': typeof CoachSubscriptionsRoute
  '/coach/training': typeof CoachTrainingRoute
  '/portal/diet': typeof PortalDietRoute
  '/portal/exercises': typeof PortalExercisesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/weight': typeof PortalWeightRoute
  '/portal/workouts': typeof PortalWorkoutsRoute
  '/coach/': typeof CoachIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/coach/clients_/$clientId': typeof CoachClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coach'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/login'
    | '/portal'
    | '/shop'
    | '/coach/clients'
    | '/coach/diet'
    | '/coach/galleries'
    | '/coach/products'
    | '/coach/schedules'
    | '/coach/subscriptions'
    | '/coach/training'
    | '/portal/diet'
    | '/portal/exercises'
    | '/portal/settings'
    | '/portal/weight'
    | '/portal/workouts'
    | '/coach/'
    | '/portal/'
    | '/coach/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/login'
    | '/shop'
    | '/coach/clients'
    | '/coach/diet'
    | '/coach/galleries'
    | '/coach/products'
    | '/coach/schedules'
    | '/coach/subscriptions'
    | '/coach/training'
    | '/portal/diet'
    | '/portal/exercises'
    | '/portal/settings'
    | '/portal/weight'
    | '/portal/workouts'
    | '/coach'
    | '/portal'
    | '/coach/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coach'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/login'
    | '/portal'
    | '/shop'
    | '/coach/clients'
    | '/coach/diet'
    | '/coach/galleries'
    | '/coach/products'
    | '/coach/schedules'
    | '/coach/subscriptions'
    | '/coach/training'
    | '/portal/diet'
    | '/portal/exercises'
    | '/portal/settings'
    | '/portal/weight'
    | '/portal/workouts'
    | '/coach/'
    | '/portal/'
    | '/coach/clients_/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachRoute: typeof CoachRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/portal/workouts': {
      id: '/portal/workouts'
      path: '/workouts'
      fullPath: '/portal/workouts'
      preLoaderRoute: typeof PortalWorkoutsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/weight': {
      id: '/portal/weight'
      path: '/weight'
      fullPath: '/portal/weight'
      preLoaderRoute: typeof PortalWeightRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/exercises': {
      id: '/portal/exercises'
      path: '/exercises'
      fullPath: '/portal/exercises'
      preLoaderRoute: typeof PortalExercisesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/diet': {
      id: '/portal/diet'
      path: '/diet'
      fullPath: '/portal/diet'
      preLoaderRoute: typeof PortalDietRouteImport
      parentRoute: typeof PortalRoute
    }
    '/coach/training': {
      id: '/coach/training'
      path: '/training'
      fullPath: '/coach/training'
      preLoaderRoute: typeof CoachTrainingRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/subscriptions': {
      id: '/coach/subscriptions'
      path: '/subscriptions'
      fullPath: '/coach/subscriptions'
      preLoaderRoute: typeof CoachSubscriptionsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/schedules': {
      id: '/coach/schedules'
      path: '/schedules'
      fullPath: '/coach/schedules'
      preLoaderRoute: typeof CoachSchedulesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/products': {
      id: '/coach/products'
      path: '/products'
      fullPath: '/coach/products'
      preLoaderRoute: typeof CoachProductsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/galleries': {
      id: '/coach/galleries'
      path: '/galleries'
      fullPath: '/coach/galleries'
      preLoaderRoute: typeof CoachGalleriesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/diet': {
      id: '/coach/diet'
      path: '/diet'
      fullPath: '/coach/diet'
      preLoaderRoute: typeof CoachDietRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clients': {
      id: '/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof CoachClientsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clients_/$clientId': {
      id: '/coach/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/coach/clients/$clientId'
      preLoaderRoute: typeof CoachClientsClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachClientsRoute: typeof CoachClientsRoute
  CoachDietRoute: typeof CoachDietRoute
  CoachGalleriesRoute: typeof CoachGalleriesRoute
  CoachProductsRoute: typeof CoachProductsRoute
  CoachSchedulesRoute: typeof CoachSchedulesRoute
  CoachSubscriptionsRoute: typeof CoachSubscriptionsRoute
  CoachTrainingRoute: typeof CoachTrainingRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachClientsClientIdRoute: typeof CoachClientsClientIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientsRoute: CoachClientsRoute,
  CoachDietRoute: CoachDietRoute,
  CoachGalleriesRoute: CoachGalleriesRoute,
  CoachProductsRoute: CoachProductsRoute,
  CoachSchedulesRoute: CoachSchedulesRoute,
  CoachSubscriptionsRoute: CoachSubscriptionsRoute,
  CoachTrainingRoute: CoachTrainingRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachClientsClientIdRoute: CoachClientsClientIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface PortalRouteChildren {
  PortalDietRoute: typeof PortalDietRoute
  PortalExercisesRoute: typeof PortalExercisesRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalWeightRoute: typeof PortalWeightRoute
  PortalWorkoutsRoute: typeof PortalWorkoutsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDietRoute: PortalDietRoute,
  PortalExercisesRoute: PortalExercisesRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalWeightRoute: PortalWeightRoute,
  PortalWorkoutsRoute: PortalWorkoutsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachRoute: CoachRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
